export enum ConfFileNames {
  SWC_CONFIG = ".swcrc",
  ESLINT_IGNORE = ".eslintignore",
  ESLINT_RC = ".eslintrc.json",
  GIT_HOOK_TASKS_CONFIG = "git-hook-tasks.config.json",
  GIT_IGNORE = ".gitignore",
  JEST_CONFIG = "jest.config.js",
  GEST_CONFIG = "gest.config.mjs",
  LICENSE = "LICENSE",
  NPM_IGNORE = ".npmignore",
  NPM_CONFIG = ".npmrc",
  PACKAGE = "package.json",
  PRETTIER_RC = ".prettierrc.mjs",
  PRETTIER_IGNORE = ".prettierignore",
  TS_CONFIG = "tsconfig.json",
  VS_CODE_SETTINGS = "settings.json",
  YARN_RC = ".yarnrc.yml",
}
