export enum ConfFileNames {
  ESLINT_IGNORE = ".eslintignore",
  ESLINT_RC = ".eslintrc.json",
  GIT_HOOK_TASKS_CONFIG = "git-hook-tasks.config.json",
  GIT_IGNORE = ".gitignore",
  JEST_CONFIG = "jest.config.js",
  LICENSE = "LICENSE",
  NPM_IGNORE = ".npmignore",
  NPM_CONFIG = ".npmrc",
  PACKAGE = "package.json",
  PRETTIER_RC = ".prettierrc.json",
  TS_CONFIG = "tsconfig.json",
  VS_CODE_SETTINGS = ".vscode/settings.json",
  YARN_RC = ".yarnrc.yml",
}
