export const DEV_DEPS = [
  "@swc/core",
  "@swc/jest",
  "@types/jest",
  "@typescript-eslint/eslint-plugin",
  "@typescript-eslint/parser",
  "eslint-config-prettier",
  "eslint-plugin-prettier",
  "eslint",
  "husky",
  "jest",
  "ncpa0cpl/git-hook-tasks",
  "prettier-plugin-jsdoc",
  "prettier",
  "typescript",
];
